[tool.poetry]
name = "fitsviewer"
version = "0.1.0"
description = "FITS header viewer"
authors = ["vtcloud"]
license = "CC0 v1.0 Universal"
readme = "README.rst"
packages = [
    { include = "fitsviewer" },
    { include = "fitsviewer/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[project.scripts]
fitsviewer = "fitsviewer.execfv"

[build-system]
#requires = ["poetry-core>=1.0.0"]
#build-backend = "poetry.core.masonry.api"
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
